/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import java.util.PriorityQueue; 
import java.util.Scanner; 
import java.util.Comparator; 
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

/**
 *
 * @author dichha
 */
class HuffmanNodeII{
    int data; 
    char c; 
    
    HuffmanNodeII left; 
    HuffmanNodeII right; 
    
}

class MyComparatorII implements Comparator<HuffmanNodeII>{
    public int compare(HuffmanNodeII x, HuffmanNodeII y){
        return x.data - y.data; 
    }
}
public class HuffmanDecoding {
    // recursive function to print the huffman-code through the tree traversal. 
    // Here's the huffman - code generator
    public static void printCode(HuffmanNodeII root, String s){
        // base case: if the left and right are null
        // then it's a leaf node and we print the code s generated by 
        // traversing the tree. 
        
        
        if(root.left == null && root.right == null && Character.isLetter(root.c)){
            System.out.println(root.c + ": " + s);
            return; 
        }
        
        // if we go left then add '0' to the code.
        // if we go right then we add '1' to the code. 
        
        // recursive calls for left and right sub-tree of the generated tree. 
        
        printCode(root.left, s + "0"); 
        printCode(root.right, s + "1"); 
            
    }
    public static HuffmanNodeII huffmanEncoding(PriorityQueue<HuffmanNodeII> q, char[] charArray, int[] charFreq, int n){
       
        
        for(int i=0; i<n; i++){
            //creating a huffman code obj and adding it  to the priority-queue.
            HuffmanNodeII hn = new HuffmanNodeII(); 
            hn.c = charArray[i]; 
            hn.data = charFreq[i]; 
            
            hn.left = null; 
            hn.right = null; 
            
            // add functions adds the huffman node to the queue
            
            q.add(hn); 
            
        }
        // create a root node
        
        HuffmanNodeII root = null; 
        
        // Here we will extrack the two minimum valu from the heap each time until its size reduces to 1, 
        // extract until all the nodes are extracted
        
        while(q.size() > 1){
            // first min extract
            HuffmanNodeII x = q.peek(); 
            q.poll(); 
            
            // second min = q.peek(); 
            HuffmanNodeII y = q.peek(); 
            q.poll(); 
            
            // new node f which is equal
            HuffmanNodeII f = new HuffmanNodeII(); 
            
            // to the sum of the frequency of the two nodes
            // assigning values to the f node. 
            
            f.data = x.data + y.data; 
            f.c = '-'; 
            
            // first extracted node as left child. 
            f.left = x; 
            
            // second extracted node as the right child
            f.right = y; 
            
            // marking the f node as the root node
            root = f; 
            
            // add this to the priority-queue
            q.add(f);     
            
        }
        return root; 
    }
    static Map<Character, Integer> calcFreq(String s){
        Map<Character, Integer> map = new HashMap<Character, Integer>(); 
        for(int i=0; i<s.length(); i++){
            char c = s.charAt(i); 
            if(map.containsKey(c)){
                map.put(c, map.get(c)+1); 
            }else{
                map.put(c, 1);
            }
        }
        
        return map; 
                
    }
    
    public static void main(String[] args){
         
        
    
       
        // number of characters
        String str = "geeksforgeeks"; 
        
        PriorityQueue<HuffmanNodeII> q = new PriorityQueue<HuffmanNodeII>(str.length(), new MyComparatorII());
        Map<Character,Integer> map = calcFreq(str);
        Set set= map.keySet(); 
        Iterator it = set.iterator(); 
        
        char[] charArr = new char[set.size()]; 
        int[] charFreq = new int[set.size()];
        Object[] chars = set.toArray();
        
        for(int i=0; i<set.size(); i++){
            charFreq[i] = map.get(chars[i]);
            charArr[i] = (char)chars[i]; 
        }
        /*
        for(int i=0; i<set.size(); i++){
            System.out.print(charArr[i] + ":" + charFreq[i] +"   "); 
        }
        */
        HuffmanNodeII root = huffmanEncoding(q, charArr, charFreq, set.size()); 
        
        
        /*
        
       
        while(it.hasNext()){
             = it.next();
            charArr[i] = c; 
            charFreq[i] = map.get(c);
            i++; 
            
        }
        for(int k=0; i<set.size(); k++){
            System.out.print(charArr[k] + ": " + charFreq[k]);
        }
 */
        
        
        // creating a priority queue q. 
        // makes a min priority queue(min-heap)
        
  
        // print the codes by traversing the tree
        printCode(root, ""); 
                
        
    }
    
    
}
